; PlatformIO Project Configuration File for MCB_T4.1
;
; This repository is designed to work with both PlatformIO and Arduino 
;
; To use with PlatformIO: 
; cd src; ln -s .. MCB_T4.1.ino MCB_T4.1.cpp
;
; To use with ArduinoIDE:
; rm -rf .pio/
; rm src/MCB_T4.1.cpp
;
; Note that one of _INST_RATS, INST_FLOATS, or INST_RACHUTS must be defined. 

[env]
platform = teensy
board = teensy41
framework = arduino
build_flags = 
  -I./src
  -I./
lib_deps = 
  https://github.com/kalnajslab-org/TeensyEEPROM.git
  https://github.com/kalnajslab-org/MCBComm.git
  https://github.com/kalnajslab-org/SafeBuffer.git
  https://github.com/kalnajslab-org/Technosoft.git
  https://github.com/kalnajslab-org/Tsensor1Wire.git
  https://github.com/kalnajslab-org/StratoLinduino.git
  https://github.com/kalnajslab-org/SerialComm.git
  https://github.com/tonton81/WDT_T4.git
  mikalhart/TinyGPSPlus@^1.1.0
monitor_port=/dev/cu.usbmodem162941601

[env:rachuts]
build_flags = 
  ${env.build_flags}
  -DINST_RACHUTS=1

[env:rats]
build_flags = 
  ${env.build_flags}
  -DINST_RATS=1

[env:floats]
build_flags = 
  ${env.build_flags}
  -DINST_FLOATS=1